added basic config stuff
chinese-board-games/luzhanqi-backend pull request #54
Opened 2023-11-08 09:46 UTC by fireteam99

# Description

One to two sentence description.

## Type of Change

- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Documentation update

## Checklist

- [ ] Unit/integration tests
- [ ] Documentation

2023-11-08 18:56 UTC, iankhou requested changes

2023-11-08 21:17 UTC, iankhou commented on src/lzqgame.ts
> +    });
Nevermind, it was my own linter issue.

2023-11-09 09:33 UTC, fireteam99 commented on src/lzqgame.ts
> +    });
addressed async

2023-11-09 09:34 UTC, fireteam99 commented on src/models/Game.ts
> +    _id: Types.ObjectId;
Yes, it's required for subdocuments: https://mongoosejs.com/docs/typescript/subdocuments.html

2023-11-10 10:58 UTC, fireteam99 commented on package.json
> +        "mongoose": "^8.0.0",
Upgrading to 8 was the only way to get subdocuments to work with TS ([docs](https://mongoosejs.com/docs/typescript/subdocuments.html)). There don't appear to be any regressions so we should be ok

2023-11-12 21:40 UTC, iankhou requested changes

2023-11-12 21:40 UTC, iankhou commented on src/lzqgame.ts
> +    roomId: string,
roomId and gameId are both strings of the same value (stringified Mongo ObjectId). Should be only one param that represents both (roomId on client-side, gid on server-side).

2023-11-14 20:46 UTC, iankhou approved these changes
Nice

2023-11-15 03:14 UTC, merged